modLoader="javafml"
loaderVersion="1"
license="MPL-2.0"
#issueTrackerURL="https://legacy.curseforge.com/minecraft/mc-mods/better-clouds-forge" todo add issue tracker

[[mods]]
modId="betterclouds"
version="1.2.1-neoforge"
displayName="Better Clouds"
logoFile="betterclouds/icon.png"
authors="Qendolin, Officialy (Forge Port)"

description='Beautiful clouds in touch with the vanilla style.'

[[dependencies.betterclouds]]
modId="neoforge"
mandatory=true
versionRange = "[20,)"
ordering="NONE"
side="CLIENT"

[[dependencies.betterclouds]]
modId="minecraft"
mandatory=true
versionRange="[1.20.2,1.21)"
ordering="NONE"
side="CLIENT"

[[dependencies.betterclouds]]
modId = "yet_another_config_lib_v3"
mandatory = true
versionRange = "[3.2.1,)"
ordering = "NONE"
side = "CLIENT"

[[mixins]]
config = "betterclouds.mixins.json"